### PR TITLE
Add roadmap feature to landing page + small fixes

### LINKED ISSUE #468: Clicking on the logo doesn't scroll to the top
Image

Clicking on the logo removes the `#features` hash from the URL but it doesn't scroll to the top (which I would expect)

### PR DESCRIPTION
**Pull request by vincanger**
https://github.com/user-attachments/assets/c4d8aeb0-626f-45f6-b3c2-afb0faae29d7

## Description

Introduces a new Roadmap component and related operations to the landing page, adds a getGithubRoadmap query, and updates navigation constants. 

Also updates the nav bar scrolling ( fixes #468 ) and the hero section orbit overflow behavior.

## Contributor Checklist

> Make sure to do the following steps if they are applicable to your PR:

- [ ] **Update e2e tests**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/template/e2e-tests](/template/e2e-tests) also.
- [x] **Update demo app**: If you changed the [/template/app](/template/app), then make sure to do any neccessary updates to [/opensaas-sh/app_diff](/opensaas-sh/app_diff) also. Check [/opensaas-sh/README.md](/opensaas-sh/README.md) for details.
- [ ] **Update docs**: If needed, update the [/opensaas-sh/blog/src/content/docs](/opensaas-sh/blog/src/content/docs).

### CODE REVIEW

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
++const CACHE_DURATION = 4 * 60 * 60 * 1000
++
++export const getGithubRoadmap: GetGithubRoadmap<void, RoadmapData> = async () => {
++  const currentTime = Date.now()
++
++  if (cachedData && currentTime - lastFetchTime < CACHE_DURATION) {
++    return cachedData
++  }
++
++  const token = process.env.GITHUB_ROADMAP_TOKEN
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: Please add `GITHUB_ROADMAP_TOKEN` to the shared `dotenv-vault`.

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 2]
```diff
@@ -0,0 +1,211 @@
+--- template/app/src/landing-page/operations.ts
++++ opensaas-sh/app/src/landing-page/operations.ts
+@@ -0,0 +1,208 @@
++import type { GetGithubRoadmap } from 'wasp/server/operations'
++import * as z from 'zod'
++
++const ORG_NAME = "wasp-lang"
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: `GITHUB_ORG_NAME`

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
++const PROJECT_NUMBER = 6
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: `OPEN_SAAS_GITHUB_PROJECT_NUMBER`

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 4]
```diff
@@ -0,0 +1,211 @@
...
++        items: z.object({
++          nodes: z.array(ProjectV2ItemSchema)
++        }).nullish()
++      }).nullish()
++    }).nullish()
++  }).nullish(),
++  errors: z.array(z.any()).nullish()
++})
++
++export enum EpicStatus {
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: `GithubEpicStatus`

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 5]
```diff
@@ -0,0 +1,211 @@
...
++
++export type EpicStats = {
++  name: string
++  total: number
++  done: number
++  status: EpicStatus
++  url: string
++}
++
++type RoadmapData = EpicStats[]
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: I don't think we really need this.
Inline is fine.

e.g. `export const getGithubRoadmap: GetGithubRoadmap<void, GithubEpicStats[]> = async () => {`

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 6]
```diff
@@ -0,0 +1,211 @@
...
++
++let cachedData: RoadmapData | null = null
++let lastFetchTime = 0
++const CACHE_DURATION = 4 * 60 * 60 * 1000
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: Can we note somehow that this is 4 hours?

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 7]
```diff
@@ -0,0 +1,211 @@
...
++let lastFetchTime = 0
++const CACHE_DURATION = 60 * 60 * 1000
++
++export const getGithubRoadmap: GetGithubRoadmap<void, RoadmapData> = async () => {
++  const currentTime = Date.now()
++
++  if (cachedData && currentTime - lastFetchTime < CACHE_DURATION) {
++    return cachedData
++  }
++
```
[the remark this answers is not in the document]
Comment (FranjoMindek) [reply opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: No thank you for now.

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 8]
```diff
@@ -0,0 +1,211 @@
...
++    if (validatedResponse.errors) {
++      console.error("GitHub API Errors:", validatedResponse.errors)
++      throw new Error("GitHub API returned errors")
++    }
++
++    const nodes = validatedResponse.data?.organization?.projectV2?.items?.nodes || []
++    const statusFieldName = "Status"
++
++    const BASE_PROJECT_URL = "https://github.com/orgs/wasp-lang/projects/6/views/1?pane=issue&itemId="
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: We can interpolate with out constants:
```ts
const BASE_PROJECT_URL = `https://github.com/orgs/${GITHUB_ORG_NAME}/projects/${OPEN_SAAS_GITHUB_PROJECT_NUMBER}/views/1?pane=issue&itemId=`
```

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 9]
```diff
@@ -0,0 +1,211 @@
...
++
++    const statusOrder = { 
++      [EpicStatus.InProgress]: 0, 
++      [EpicStatus.Planned]: 1, 
++      [EpicStatus.Ideas]: 2, 
++      [EpicStatus.Done]: 3 
++    }
++    
++    epics.sort((a, b) => {
++      const orderA = statusOrder[a.status] ?? 99
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: The `?? 99` is unnecessary here because we always set the `status`.

We can simplify:
```ts
epics.sort((a, b) => statusOrder[a.status] - statusOrder[b.status])
```

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 10]
```diff
@@ -0,0 +1,211 @@
...
++  Done = "Done"
++}
++
++export type EpicStats = {
++  name: string
++  total: number
++  done: number
++  status: EpicStatus
++  url: string
++}
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: Maybe just `GithubEpic`

I would make it more clear what the fields are:

```ts
export type GithubEpic = {
  name: string
  status: GithubEpicStatus
  totalIssues: number
  doneIssues: number
  url: string
}
```

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 11]
```diff
@@ -0,0 +1,211 @@
+--- template/app/src/landing-page/operations.ts
++++ opensaas-sh/app/src/landing-page/operations.ts
+@@ -0,0 +1,208 @@
++import type { GetGithubRoadmap } from 'wasp/server/operations'
++import * as z from 'zod'
++
++const ORG_NAME = "wasp-lang"
++const PROJECT_NUMBER = 6
++
++const GithubIssueSchema = z.object({
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: I would maybe move the schemas below the `getGithubRoadmap`.

So global constants -> exported types/enums -> exported function with the variables we defined outside of it -> schemas.

Schemas don't really help us understand the file before we need them, and we only need them after we start reading the parsing part of `getGithubRoadmap`.

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 12]
```diff
@@ -0,0 +1,211 @@
...
++    }
++    
++    epics.sort((a, b) => {
++      const orderA = statusOrder[a.status] ?? 99
++      const orderB = statusOrder[b.status] ?? 99
++      return orderA - orderB
++    })
++
++    cachedData = epics
++    lastFetchTime = currentTime
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: It feels weird that we set it here because we've defined `currentTime` way before.
I forgot about it till I got here.

We could do it at the start:
```ts
export const getGithubRoadmap: GetGithubRoadmap<void, GithubEpic[]> = async () => {
  const currentTime = Date.now()
  if (githubEpicsCache && currentTime - lastFetchTime < CACHE_DURATION) {
    return githubEpicsCache
  } else {
    lastFetchTime = currentTime
  }
```

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff (hunk 1 above)
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: We can go full name `githubRoadmapToken`

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 13]
```diff
@@ -0,0 +1,211 @@
...
++  name: string
++  total: number
++  done: number
++  status: EpicStatus
++  url: string
++}
++
++type RoadmapData = EpicStats[]
++
++let cachedData: RoadmapData | null = null
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: We can try to be more specific.
Cached data of what? `githubEpicsCache` maybe?

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 14]
```diff
@@ -0,0 +1,211 @@
...
++    return cachedData
++  }
++
++  const token = process.env.GITHUB_ROADMAP_TOKEN
++  if (!token) {
++    console.warn("GITHUB_ROADMAP_TOKEN is not set")
++    return []
++  }
++
++  const query = `
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: `githubGraphQlQuery` or similar.

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 15]
```diff
@@ -0,0 +1,211 @@
...
++    query($org: String!, $number: Int!) {
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff:50]: I wish this could be tidier but I guess it can't be without installing any libraries.
I guess using the REST API doesn't help?

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff [hunk 16]
```diff
@@ -0,0 +1,150 @@
...
++
++        <div className="grid gap-6 md:grid-cols-4">
++          {[EpicStatus.Ideas, EpicStatus.Planned, EpicStatus.InProgress, EpicStatus.Done].map((status) => {
++            const statusEpics = epics.filter((e: EpicStats) => e.status === status);
++            const borderColor = getBorderColor(status);
++            const statusColor = getStatusColor(status);
++            
++            return (
++              <div key={status} className="flex flex-col gap-4">
++                <div className={`flex items-center justify-center p-3 rounded-lg border ${borderColor} ${statusColor.split(' ')[0]} bg-opacity-20`}>
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: Maybe the bg could be a bit darker on dark mode? e.g. `bg-opacity-10`

Image

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff [hunk 17]
```diff
@@ -0,0 +1,211 @@
...
++      throw new Error("GitHub API returned errors")
++    }
++
++    const nodes = validatedResponse.data?.organization?.projectV2?.items?.nodes || []
++    const statusFieldName = "Status"
++
++    const BASE_PROJECT_URL = "https://github.com/orgs/wasp-lang/projects/6/views/1?pane=issue&itemId="
++
++    const epics: EpicStats[] = nodes
++      .filter((node) => {
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: This can be `.filter((node) => node.content?.issueType?.name === "Epic")`

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff [hunk 18]
```diff
@@ -0,0 +1,150 @@
...
++    return (
++      <div className="text-center py-12 text-red-500">
++        Failed to load roadmap
++      </div>
++    );
++  }
++
++  if (!epics || epics.length === 0) return null;
++
++  const getStatusColor = (status: EpicStatus) => {
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: This function can go out of the component.

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff [hunk 19]
```diff
@@ -0,0 +1,150 @@
...
++      case EpicStatus.InProgress:
++        return "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300 border-yellow-200 dark:border-yellow-800";
++      case EpicStatus.Done:
++        return "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300 border-purple-200 dark:border-purple-800";
++      default:
++        return "bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 border-gray-200 dark:border-gray-700";
++    }
++  };
++
++  const getProgressBarColor = (status: EpicStatus) => {
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: Same is for all CSS functions, they all can be defined in the outside. They you don't have to re-create them on each re-render.

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff [hunk 20]
```diff
@@ -0,0 +1,150 @@
...
++          <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl dark:text-white">
++            The Roadmap
++          </h2>
++          <p className="mt-4 text-lg leading-8 text-gray-600 dark:text-gray-300">
++            High-level topics we are planning and working on.
++          </p>
++        </div>
++
++        <div className="grid gap-6 md:grid-cols-4">
++          {[EpicStatus.Ideas, EpicStatus.Planned, EpicStatus.InProgress, EpicStatus.Done].map((status) => {
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: `Object.values(GithubEpicStatus)`,  they we don't need to update if we change states.

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff [hunk 21]
```diff
@@ -0,0 +1,150 @@
...
++            const statusEpics = epics.filter((e: EpicStats) => e.status === status);
++            const borderColor = getBorderColor(status);
++            const statusColor = getStatusColor(status);
++            
++            return (
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: Ideally we would extra these two into separate components.
e.g. `RoadmapStatusColumn` and `RoadmapEpic`

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff (hunk 16 above)
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: Something here with `statusColor` is wrong.
We only ever take the first and second class out of the `statusColor`. Why do we define the rest of it then? Should it actually be `getStatusBackground` and `getStatusTextColor`?

Any way all of these issues would be a bit nicer to solve if you extracted the two subcomponents you're rendering into separate components.

Maybe the solution is to simplify the number of different color variants. e.g. only 2 blues/greens... used

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff [hunk 22]
```diff
@@ -0,0 +1,150 @@
...
++                    
++                    return (
++                      <a 
++                        key={epic.name} 
++                        href={epic.url}
++                        target="_blank"
++                        rel="noreferrer"
++                        className={`group flex flex-col gap-3 rounded-xl border p-5 transition-all hover:shadow-md border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900/50 ${hoverBorderColor} block`}
++                      >
++                        <h4 className="font-semibold text-base text-gray-900 dark:text-white leading-tight group-hover:opacity-80 transition-opacity">
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: Why `opacity-80` on hover? Makes it seem diluted instead of "selected".

File: opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff [hunk 23]
```diff
@@ -0,0 +1,150 @@
...
++                        </h4>
++
++                        <div className="mt-auto pt-1">
++                          <div className="flex justify-between text-xs text-gray-500 dark:text-gray-400 mb-1.5">
++                            <span>Progress</span>
++                            <span>{progress}% ({epic.done}/{epic.total})</span>
++                          </div>
++                          <div className="h-1.5 w-full rounded-full bg-gray-100 dark:bg-gray-800 overflow-hidden">
++                            <div 
++                              className={`h-full rounded-full transition-all duration-500 ${progressColor}`}
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/landing-page/components/Roadmap.tsx.diff]: I guess this transition will only trigger if we re-fetch the data and we solved some issue.
Seems very rare hahaha, not that I mind it.

File: opensaas-sh/app_diff/src/client/App.tsx.diff [hunk 24]
```diff
@@ -9,3 +9,20 @@
...
+       if (element) {
+-        element.scrollIntoView();
++        const yOffset = -100;
++        const top = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
++        window.scrollTo({ top, behavior: "smooth" });
++      }
++    } else if (location.pathname === "/") {
++      // scroll to top of page
++      if (window.scrollY > 0) {
++        console.log("scrolling to top");
```
Comment (FranjoMindek) [inline opensaas-sh/app_diff/src/client/App.tsx.diff]: Yep, we don't need this `console.log`

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff (hunk 1 above)
Comment (FranjoMindek) [reply opensaas-sh/app_diff/src/landing-page/operations.ts.diff]: We added this after DM discussion, resolving.

File: opensaas-sh/app_diff/src/landing-page/operations.ts.diff (hunk 15 above)
Comment (vincanger) [reply opensaas-sh/app_diff/src/landing-page/operations.ts.diff:50]: Unfortunately we can't get this data with REST :(.
